### ISSUE TITLE
preparing the class files creates assets path under core/components/mypackage and a symlink

### ISSUE THREAD

**Issue by Bruno17** [jaredfhealy/extrabuilder#11]
Not sure, if this is a good thing, creating a symlink in the assets/components directory and the assets directory under core/components/mypackage. Trying to open the assets/components directory from manager, that symlink breaks the listing of files and subdirectories.
And not sure about the assets under a protected core folder.

**Comment by jaredfhealy** [comment]
I thought about this one as well, but the target audience for this plugin is for developers, not intended for your production site. You would use this to build your Extra or functionality and then publish with the Transport Builder. When you transport the Extra, it splits the directories out into standard directories. 

If you look at the transport for ExtraBuilder, you can see that the published Extra uses the standard directories. It is only while you're developing that it uses the symlink. Having them in a single folder allows you to use Git and commit your Extra from a single directory.

All the tutorials (or doodles, in this example) walk you through creating your development folder in your web root. You then mimic the two core and asset folder structures:

![image](https://user-images.githubusercontent.com/9794500/149782944-23f566c4-0637-4560-8fbc-b45ba2390258.png)

That is even less secure as your entire source is web accessible. If you were to do that on a production instance, it would be an even greater security risk. I could put some warnings or similar, but the target for this is Extra developers using a development instance.

**Comment by jaredfhealy** [comment]
That is good to know that it breaks using the file browser on the /components/ directory though. I'll keep this open to see if I can prevent that from happening.

Error: Unsupported symlink when opening /assets/components/ through File browser.

![image](https://user-images.githubusercontent.com/9794500/149785493-4611ac70-5dd0-4bcb-8e99-011edc9899fe.png)

**Comment by Bruno17** [comment]
Usually I'm using GPM for building and have a packages directory under the web root (configurable by systemsettings).
Maybe, it would be a nice thing, if your ExtraBuilder and GPM would be compatible and use the same directories for building.

**Comment by jaredfhealy** [comment]
Definitely something to look at. When I was first building this I really wanted a simple interface to create the tables and structure that was quicker and more intuitive. When I looked at GPM it seemed to be more command line. I need to test it out and see how it works.

I think GPM uses configuration files more as well, where my approach is to build all elements in the MODX instance and use the transport to create a "backup-0.0.0.transport.zip" that can be used to restore all the elements.

**Comment by Bruno17** [comment]
I also found it easier to create and maintain all elements within the MODX manager all the time.
Have also created a Helper https://github.com/Bruno17/migxGpmHelper for exporting elements and my assets and core - files to the GPM package directory and prepare the GPM config-file.
But this did make it a bit hard to pull PRs to my Extras back into my dev installation.

I'm just started to build everything withing the GPM package folder now and I must say, this makes developing so much easier.

**Comment by jaredfhealy** [comment]
@Bruno17 
I should have a deployment later today that corrects the path override feature. You would then be able to set your core and asset paths to whatever you want.

![image](https://user-images.githubusercontent.com/9794500/152694840-8e4e81b1-7dc1-42f2-9397-e13f486299e0.png)

**Comment by jaredfhealy** [comment]
The dependency on symlinks has been removed in favor of syncing the assets directory if building inside the core components folder. Also confirmed the override functionality works correctly to allow building in any folder from web root up.

The latest deployment incorporates these changes.
