### ISSUE TITLE
Ability to import from existing tables

### ISSUE THREAD

**Issue by jaredfhealy** [jaredfhealy/extrabuilder#2]
Allow selection of tables to include in your package. The script referenced below builds from all tables if a common prefix was not used. As a user, I can use a contains search to find and select the tables I want included in my build.

Once imported, I can generate the schema and package from there after confirming. Also add the option to sync with the database. Users may have invested in DB tools to manage their database and may prefer that method. Or they may like phpMyAdmin. This way, they can use their preferred tool and still have it build and keep the schema files in sync.

https://docs.modx.com/current/en/extending-modx/xpdo/custom-models/generating-the-model/reverse-engineer

**Comment by jaredfhealy** [comment]
Completed feature and merged to main branch.

After selecting a package, you will have an option to "Add Existing Tables to Package"
![image](https://user-images.githubusercontent.com/9794500/105654022-5df09100-5e7a-11eb-9fb2-2308dea86b6e.png)

This pops up a modal to search for tables and include them. This varies from the table prefix method slightly. Any table containing the search value will be displayed to select and include. You must manually include it rather than just grabbing all tables that match as the script method referenced here: https://docs.modx.com/current/en/extending-modx/xpdo/custom-models/generating-the-model/reverse-engineer

![image](https://user-images.githubusercontent.com/9794500/105654204-bd4ea100-5e7a-11eb-83b7-cf5ab7d09124.png)

Clicking on the "Add Selected Tables..." button runs through a modified version of the Modx reverse engineer script and creates the Object and Field entries in the ExtraBuilder tables. Then you can preview and generate as normal from there.

**Comment by ChrstnMgcn** [comment]
Hi @jaredfhealy!

I had been looking for a replacement of CMPGenerator and found the [integration with MIGX](https://community.modx.com/t/extrabuilder-migx-cmp-walkthrough-video/4979/10) perfect for a some current MODX3 projects.

I primarily use Navicat for DB management and the Import/Reverse Engineer feature would be perfect, but I don't see it in the current version. Am I missing it or was it removed for MODX3?
